export interface ComponentItem {
  id: string
  name: string
  value?: string
  category: string
  badge?: string
  badgeColor?: string
  borderColor?: string
  polarityWarning?: boolean
  description?: string
}

export interface ComponentCategory {
  id: string
  name: string
  icon: string
  count: number
  components: ComponentItem[]
}

export const componentsData: ComponentCategory[] = [
  {
    id: 'passives',
    name: 'PASSIVES',
    icon: '⚡',
    count: 26,
    components: [
      { id: 'res-1k', name: 'Resistor 1kΩ', value: '1kΩ', category: 'Passives', borderColor: 'var(--amber)' },
      { id: 'res-10k', name: 'Resistor 10kΩ', value: '10kΩ', category: 'Passives' },
      { id: 'res-100', name: 'Resistor 100Ω', value: '100Ω', category: 'Passives' },
      { id: 'res-220', name: 'Resistor 220Ω', value: '220Ω', category: 'Passives' },
      { id: 'res-470', name: 'Resistor 470Ω', value: '470Ω', category: 'Passives' },
      { id: 'pot-10k', name: 'Variable Resistor (Pot)', value: '10kΩ', category: 'Passives' },
      { id: 'trim-500', name: 'Trimmer Potentiometer', value: '500Ω', category: 'Passives' },
      { id: 'cap-100n', name: 'Capacitor 100nF', value: '100nF', category: 'Passives', borderColor: 'var(--cyan)' },
      { id: 'cap-10u', name: 'Capacitor 10µF', value: '10µF', category: 'Passives' },
      { id: 'cap-100u', name: 'Capacitor 100µF', value: '100µF', category: 'Passives' },
      { id: 'cap-1000u', name: 'Capacitor 1000µF Electrolytic', value: '1000µF', category: 'Passives', polarityWarning: true },
      { id: 'cap-10p', name: 'Capacitor 10pF Ceramic', value: '10pF', category: 'Passives' },
      { id: 'tant-10u', name: 'Tantalum Cap 10µF', value: '10µF', category: 'Passives', polarityWarning: true },
      { id: 'supercap-1f', name: 'Supercapacitor 1F', value: '1F', category: 'Passives' },
      { id: 'ind-100u', name: 'Inductor 100µH', value: '100µH', category: 'Passives' },
      { id: 'ind-1m', name: 'Inductor 1mH', value: '1mH', category: 'Passives' },
      { id: 'ind-10m', name: 'Inductor 10mH', value: '10mH', category: 'Passives' },
      { id: 'toroid-100u', name: 'Toroidal Inductor', value: '100µH', category: 'Passives' },
      { id: 'xtal-16m', name: 'Crystal 16MHz', value: '16MHz', category: 'Passives' },
      { id: 'xtal-8m', name: 'Crystal 8MHz', value: '8MHz', category: 'Passives' },
      { id: 'xtal-32k', name: 'Crystal 32.768kHz', value: '32.768kHz', category: 'Passives' },
      { id: 'ntc-10k', name: 'NTC Thermistor 10kΩ', category: 'Passives' },
      { id: 'ptc', name: 'PTC Thermistor', category: 'Passives' },
      { id: 'ldr', name: 'LDR Photoresistor', category: 'Passives' },
      { id: 'mov', name: 'Varistor MOV', category: 'Passives' },
      { id: 'ferrite', name: 'Ferrite Bead', category: 'Passives' },
    ]
  },
  {
    id: 'semiconductors',
    name: 'SEMICONDUCTORS',
    icon: '💡',
    count: 32,
    components: [
      { id: 'led-red', name: 'LED Red 5mm', category: 'Semiconductors', borderColor: '#ff0044' },
      { id: 'led-green', name: 'LED Green 5mm', category: 'Semiconductors', borderColor: '#00ff88' },
      { id: 'led-blue', name: 'LED Blue 5mm', category: 'Semiconductors', borderColor: '#0088ff' },
      { id: 'led-yellow', name: 'LED Yellow 5mm', category: 'Semiconductors' },
      { id: 'led-white', name: 'LED White 5mm', category: 'Semiconductors' },
      { id: 'led-ir', name: 'LED IR 5mm', category: 'Semiconductors' },
      { id: 'led-uv', name: 'LED UV 5mm', category: 'Semiconductors' },
      { id: 'led-rgb', name: 'LED RGB Common Cathode', category: 'Semiconductors', badge: 'RGB' },
      { id: 'ws2812b', name: 'WS2812B Addressable LED', category: 'Semiconductors', badge: 'Smart' },
      { id: 'ws2812b-strip', name: 'WS2812B Strip 8x', category: 'Semiconductors', badge: 'Strip' },
      { id: 'diode-1n4007', name: 'Diode 1N4007', category: 'Semiconductors' },
      { id: 'diode-1n4148', name: 'Diode 1N4148', category: 'Semiconductors' },
      { id: 'zener-5v1', name: 'Zener 5.1V', category: 'Semiconductors' },
      { id: 'zener-3v3', name: 'Zener 3.3V', category: 'Semiconductors' },
      { id: 'schottky-1n5819', name: 'Schottky 1N5819', category: 'Semiconductors' },
      { id: 'schottky-bat43', name: 'Schottky BAT43', category: 'Semiconductors' },
      { id: 'npn-2n2222', name: 'NPN Transistor 2N2222', category: 'Semiconductors' },
      { id: 'npn-bc547', name: 'NPN Transistor BC547', category: 'Semiconductors' },
      { id: 'pnp-bc557', name: 'PNP Transistor BC557', category: 'Semiconductors' },
      { id: 'pnp-2n3906', name: 'PNP Transistor 2N3906', category: 'Semiconductors' },
      { id: 'mosfet-irfz44n', name: 'MOSFET N-Ch IRFZ44N', category: 'Semiconductors', badge: 'Power' },
      { id: 'mosfet-2n7000', name: 'MOSFET N-Ch 2N7000', category: 'Semiconductors' },
      { id: 'mosfet-irf9540', name: 'MOSFET P-Ch IRF9540', category: 'Semiconductors' },
      { id: 'igbt', name: 'IGBT', category: 'Semiconductors' },
      { id: 'uln2003', name: 'Darlington ULN2003', category: 'Semiconductors', badge: 'Array' },
      { id: 'opto-pc817', name: 'Optocoupler PC817', category: 'Semiconductors' },
      { id: 'opto-moc3021', name: 'Optocoupler MOC3021', category: 'Semiconductors' },
      { id: 'reg-7805', name: 'Voltage Reg 7805', category: 'Semiconductors', badge: '+5V' },
      { id: 'reg-7812', name: 'Voltage Reg 7812', category: 'Semiconductors', badge: '+12V' },
      { id: 'reg-lm317', name: 'Voltage Reg LM317', category: 'Semiconductors', badge: 'Adj' },
      { id: 'buck-lm2596', name: 'Buck Converter LM2596', category: 'Semiconductors', badge: 'Buck' },
      { id: 'ldo-ams1117', name: 'LDO 3.3V AMS1117', category: 'Semiconductors' },
    ]
  },
  {
    id: 'microcontrollers',
    name: 'MICROCONTROLLERS',
    icon: '🧠',
    count: 23,
    components: [
      { id: 'arduino-uno', name: 'Arduino Uno R3', category: 'Microcontrollers', badge: 'AVR', borderColor: 'var(--cyan)' },
      { id: 'arduino-nano', name: 'Arduino Nano', category: 'Microcontrollers', badge: 'AVR' },
      { id: 'arduino-mega', name: 'Arduino Mega 2560', category: 'Microcontrollers', badge: 'AVR' },
      { id: 'arduino-leo', name: 'Arduino Leonardo', category: 'Microcontrollers' },
      { id: 'arduino-micro', name: 'Arduino Micro', category: 'Microcontrollers' },
      { id: 'arduino-due', name: 'Arduino Due', category: 'Microcontrollers', badge: 'ARM' },
      { id: 'arduino-promini-5v', name: 'Arduino Pro Mini 5V', category: 'Microcontrollers' },
      { id: 'arduino-promini-3v3', name: 'Arduino Pro Mini 3.3V', category: 'Microcontrollers' },
      { id: 'arduino-mkr', name: 'Arduino MKR WiFi 1010', category: 'Microcontrollers', badge: 'WiFi' },
      { id: 'esp32-devkit', name: 'ESP32 DevKit V1', category: 'Microcontrollers', badge: 'WiFi+BT', borderColor: 'var(--magenta)' },
      { id: 'esp32-wroom', name: 'ESP32 WROOM-32', category: 'Microcontrollers' },
      { id: 'esp32-s3', name: 'ESP32-S3', category: 'Microcontrollers' },
      { id: 'esp8266-nodemcu', name: 'ESP8266 NodeMCU', category: 'Microcontrollers', badge: 'WiFi' },
      { id: 'esp8266-d1mini', name: 'ESP8266 Wemos D1 Mini', category: 'Microcontrollers' },
      { id: 'pico', name: 'Raspberry Pi Pico', category: 'Microcontrollers', badge: 'RP2040' },
      { id: 'pico-w', name: 'Raspberry Pi Pico W', category: 'Microcontrollers', badge: 'WiFi' },
      { id: 'pi-zero', name: 'Raspberry Pi Zero 2W', category: 'Microcontrollers' },
      { id: 'stm32-blue', name: 'STM32 Blue Pill', category: 'Microcontrollers', badge: 'ARM' },
      { id: 'stm32-black', name: 'STM32 Black Pill', category: 'Microcontrollers', badge: 'ARM' },
      { id: 'attiny85', name: 'ATtiny85', category: 'Microcontrollers' },
      { id: 'attiny2313', name: 'ATtiny2313', category: 'Microcontrollers' },
      { id: 'teensy41', name: 'Teensy 4.1', category: 'Microcontrollers', badge: 'ARM' },
      { id: 'nrf52840', name: 'nRF52840', category: 'Microcontrollers', badge: 'BLE' },
    ]
  },
  {
    id: 'sensors',
    name: 'SENSORS',
    icon: '📡',
    count: 31,
    components: [
      { id: 'dht11', name: 'DHT11 Temp+Humidity', category: 'Sensors', badge: 'Digital' },
      { id: 'dht22', name: 'DHT22 Temp+Humidity', category: 'Sensors', badge: 'Digital' },
      { id: 'ds18b20', name: 'DS18B20 Temp Probe', category: 'Sensors', badge: '1-Wire' },
      { id: 'bmp280', name: 'BMP280 Baro+Temp', category: 'Sensors', badge: 'I2C' },
      { id: 'bme280', name: 'BME280 Baro+Hum+Temp', category: 'Sensors', badge: 'I2C' },
      { id: 'mpu6050', name: 'MPU6050 Gyro+Accel', category: 'Sensors', badge: 'I2C' },
      { id: 'hcsr04', name: 'HC-SR04 Ultrasonic', category: 'Sensors', badge: 'Ultrasonic' },
      { id: 'vl53l0x', name: 'VL53L0X TOF Distance', category: 'Sensors', badge: 'Laser' },
      { id: 'pir-hcsr501', name: 'PIR Motion HC-SR501', category: 'Sensors', badge: 'Motion' },
      { id: 'mq2', name: 'MQ-2 Gas (LPG/Smoke)', category: 'Sensors', badge: 'Analog' },
      { id: 'mq3', name: 'MQ-3 Alcohol Sensor', category: 'Sensors' },
      { id: 'mq7', name: 'MQ-7 CO Sensor', category: 'Sensors' },
      { id: 'acs712-5a', name: 'ACS712 Current 5A', category: 'Sensors', badge: 'Analog' },
      { id: 'acs712-20a', name: 'ACS712 Current 20A', category: 'Sensors' },
      { id: 'ina219', name: 'INA219 Current I2C', category: 'Sensors', badge: 'I2C' },
      { id: 'pzem004t', name: 'PZEM-004T Power', category: 'Sensors', badge: 'UART' },
      { id: 'tcs3200', name: 'TCS3200 Color Sensor', category: 'Sensors', badge: 'Digital' },
      { id: 'apds9960', name: 'APDS9960 Gesture', category: 'Sensors', badge: 'I2C' },
      { id: 'lm35', name: 'LM35 Temp Analog', category: 'Sensors', badge: 'Analog' },
      { id: 'soil-moisture', name: 'Soil Moisture Sensor', category: 'Sensors' },
      { id: 'rain-sensor', name: 'Rain Sensor Module', category: 'Sensors' },
      { id: 'water-level', name: 'Water Level Sensor', category: 'Sensors' },
      { id: 'vibration-sw420', name: 'Vibration SW-420', category: 'Sensors' },
      { id: 'hall-a3144', name: 'Hall Effect A3144', category: 'Sensors' },
      { id: 'ir-obstacle', name: 'IR Obstacle Sensor', category: 'Sensors' },
      { id: 'flame-sensor', name: 'Flame Sensor', category: 'Sensors' },
      { id: 'touch-ttp223', name: 'Touch Sensor TTP223', category: 'Sensors' },
      { id: 'loadcell-hx711', name: 'Load Cell + HX711', category: 'Sensors', badge: 'Weight' },
      { id: 'max30100', name: 'MAX30100 Pulse Ox', category: 'Sensors', badge: 'I2C' },
      { id: 'fsr', name: 'Force Sensitive Resistor FSR', category: 'Sensors' },
      { id: 'sound-sensor', name: 'Sound Sensor Module', category: 'Sensors' },
    ]
  },
  {
    id: 'actuators',
    name: 'ACTUATORS',
    icon: '🔧',
    count: 23,
    components: [
      { id: 'dc-motor-5v', name: 'DC Motor 5V', category: 'Actuators', badge: 'Motor' },
      { id: 'dc-motor-12v', name: 'DC Motor 12V', category: 'Actuators', badge: 'Motor' },
      { id: 'servo-sg90', name: 'Servo SG90 9g', category: 'Actuators', badge: 'Servo' },
      { id: 'servo-mg995', name: 'Servo MG995', category: 'Actuators', badge: 'Servo' },
      { id: 'stepper-nema17', name: 'Stepper NEMA 17', category: 'Actuators', badge: 'Stepper' },
      { id: 'stepper-28byj48', name: 'Stepper 28BYJ-48', category: 'Actuators', badge: 'Stepper' },
      { id: 'l298n', name: 'L298N Motor Driver', category: 'Actuators', badge: 'Driver' },
      { id: 'l293d', name: 'L293D Motor Driver', category: 'Actuators', badge: 'Driver' },
      { id: 'drv8825', name: 'DRV8825 Stepper Driver', category: 'Actuators', badge: 'Driver' },
      { id: 'a4988', name: 'A4988 Stepper Driver', category: 'Actuators', badge: 'Driver' },
      { id: 'relay-5v', name: 'Relay 5V SPDT', category: 'Actuators', badge: 'Relay' },
      { id: 'relay-12v', name: 'Relay 12V SPDT', category: 'Actuators', badge: 'Relay' },
      { id: 'relay-2ch', name: 'Relay Module 2-Ch', category: 'Actuators', badge: 'Module' },
      { id: 'relay-4ch', name: 'Relay Module 4-Ch', category: 'Actuators', badge: 'Module' },
      { id: 'solenoid-12v', name: 'Solenoid Valve 12V', category: 'Actuators', badge: 'Solenoid' },
      { id: 'linear-actuator', name: 'Linear Actuator', category: 'Actuators', badge: 'Actuator' },
      { id: 'buzzer-active', name: 'Buzzer Active 5V', category: 'Actuators', badge: 'Audio' },
      { id: 'buzzer-passive', name: 'Buzzer Passive 5V', category: 'Actuators', badge: 'Audio' },
      { id: 'speaker-8ohm', name: 'Speaker 8Ω 0.5W', category: 'Actuators', badge: 'Audio' },
      { id: 'vibration-motor', name: 'Vibration Motor', category: 'Actuators', badge: 'Motor' },
      { id: 'mini-pump', name: 'Mini Pump 5V', category: 'Actuators', badge: 'Pump' },
      { id: 'fan-5v', name: 'Fan 5V', category: 'Actuators', badge: 'Fan' },
      { id: 'peltier', name: 'Peltier Module', category: 'Actuators', badge: 'Thermal' },
    ]
  },
  {
    id: 'displays',
    name: 'DISPLAYS',
    icon: '📺',
    count: 15,
    components: [
      { id: 'lcd-16x2-i2c', name: 'LCD 16x2 I2C', category: 'Displays', badge: 'I2C' },
      { id: 'lcd-16x2-parallel', name: 'LCD 16x2 Parallel', category: 'Displays', badge: 'Parallel' },
      { id: 'lcd-20x4-i2c', name: 'LCD 20x4 I2C', category: 'Displays', badge: 'I2C' },
      { id: 'oled-096', name: 'OLED 0.96" I2C', category: 'Displays', badge: 'OLED' },
      { id: 'oled-13', name: 'OLED 1.3" I2C', category: 'Displays', badge: 'OLED' },
      { id: 'tft-28', name: 'TFT 2.8" ILI9341', category: 'Displays', badge: 'SPI' },
      { id: '7seg-1digit', name: '7-Segment 1 Digit', category: 'Displays', badge: 'LED' },
      { id: '7seg-4digit', name: '7-Segment 4 Digit TM1637', category: 'Displays', badge: 'I2C' },
      { id: 'matrix-8x8', name: '8x8 LED Matrix', category: 'Displays', badge: 'SPI' },
      { id: 'max7219', name: 'MAX7219 LED Matrix', category: 'Displays', badge: 'SPI' },
      { id: 'epaper-29', name: 'E-Paper 2.9"', category: 'Displays', badge: 'SPI' },
      { id: 'led-bar', name: 'LED Bar Graph 10', category: 'Displays', badge: 'LED' },
      { id: 'neopixel-12', name: 'Neopixel Ring 12', category: 'Displays', badge: 'Smart' },
      { id: 'neopixel-24', name: 'Neopixel Ring 24', category: 'Displays', badge: 'Smart' },
      { id: '4digit-i2c', name: '4-Digit Segment I2C', category: 'Displays', badge: 'I2C' },
    ]
  },
  {
    id: 'communication',
    name: 'COMMUNICATION',
    icon: '📶',
    count: 16,
    components: [
      { id: 'hc05', name: 'HC-05 Bluetooth', category: 'Communication', badge: 'BT' },
      { id: 'hc06', name: 'HC-06 Bluetooth', category: 'Communication', badge: 'BT' },
      { id: 'nrf24l01', name: 'NRF24L01 2.4GHz', category: 'Communication', badge: 'RF' },
      { id: 'nrf24l01-pa', name: 'NRF24L01+PA+LNA', category: 'Communication', badge: 'RF Long' },
      { id: 'lora-sx1276', name: 'LoRa SX1276', category: 'Communication', badge: 'LoRa' },
      { id: 'lora-ra02', name: 'LoRa Ra-02', category: 'Communication', badge: 'LoRa' },
      { id: 'sim800l', name: 'SIM800L GSM', category: 'Communication', badge: 'GSM' },
      { id: 'sim7600', name: 'SIM7600 4G LTE', category: 'Communication', badge: '4G' },
      { id: 'neo6m', name: 'NEO-6M GPS', category: 'Communication', badge: 'GPS' },
      { id: 'neo8m', name: 'NEO-8M GPS', category: 'Communication', badge: 'GPS' },
      { id: 'rc522', name: 'RC522 RFID Reader', category: 'Communication', badge: 'RFID' },
      { id: 'pn532', name: 'PN532 NFC', category: 'Communication', badge: 'NFC' },
      { id: 'cp2102', name: 'USB-UART CP2102', category: 'Communication', badge: 'UART' },
      { id: 'ch340', name: 'USB-UART CH340', category: 'Communication', badge: 'UART' },
      { id: 'mcp2515', name: 'CAN Bus MCP2515', category: 'Communication', badge: 'CAN' },
      { id: 'rs485', name: 'RS485 Module', category: 'Communication', badge: 'RS485' },
    ]
  },
  {
    id: 'power',
    name: 'POWER',
    icon: '⚡',
    count: 15,
    components: [
      { id: 'batt-9v', name: '9V Battery', category: 'Power', badge: '9V' },
      { id: 'batt-aa-2x', name: 'AA Battery Pack 2x', category: 'Power', badge: '3V' },
      { id: 'batt-aa-4x', name: 'AA Battery Pack 4x', category: 'Power', badge: '6V' },
      { id: 'lipo-1000', name: 'Li-Po 3.7V 1000mAh', category: 'Power', badge: 'LiPo', borderColor: 'var(--amber)' },
      { id: 'lipo-2000', name: 'Li-Po 3.7V 2000mAh', category: 'Power', badge: 'LiPo' },
      { id: '18650', name: '18650 Cell', category: 'Power', badge: '3.7V' },
      { id: '18650-2x', name: '18650 Holder 2x', category: 'Power', badge: '7.4V' },
      { id: 'usb-powerbank', name: 'USB Power Bank Module', category: 'Power', badge: '5V' },
      { id: 'breadboard-psu', name: 'Breadboard PSU 5V/3.3V', category: 'Power', badge: 'Module' },
      { id: 'xl6009', name: 'Buck Boost XL6009', category: 'Power', badge: 'Boost' },
      { id: 'usbc-pd', name: 'USB-C PD Module', category: 'Power', badge: 'PD' },
      { id: 'solar-5v', name: 'Solar Panel 5V 1W', category: 'Power', badge: 'Solar' },
      { id: 'tp4056', name: 'TP4056 Li-Po Charger', category: 'Power', badge: 'Charger' },
      { id: 'coin-cr2032', name: 'Coin Cell CR2032', category: 'Power', badge: '3V' },
      { id: 'supercap-10f', name: 'Supercap 10F', category: 'Power', badge: 'Super' },
    ]
  },
  {
    id: 'instruments',
    name: 'INSTRUMENTS',
    icon: '🔬',
    count: 8,
    components: [
      { id: 'dmm', name: 'Digital Multimeter', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: 'VDC/VAC/ADC/Ω/Continuity' },
      { id: 'oscilloscope', name: 'Oscilloscope 2Ch', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: '100MHz simulated' },
      { id: 'logic-analyzer', name: 'Logic Analyzer 8Ch', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: 'Protocol decode' },
      { id: 'func-gen', name: 'Function Generator', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: '0.1Hz-1MHz' },
      { id: 'var-psu', name: 'Variable PSU 0-30V', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: '0-5A adjustable' },
      { id: 'freq-counter', name: 'Frequency Counter', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: '50Hz-100MHz' },
      { id: 'lcr-meter', name: 'LCR Meter', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: 'L/C/R/Z measurement' },
      { id: 'signal-tracer', name: 'Signal Tracer', category: 'Instruments', badge: 'Virtual', borderColor: 'var(--green)', description: 'Audio frequency' },
    ]
  },
]

export const allComponents = componentsData.flatMap(cat => cat.components)
